### ISSUE TITLE
admin dashboard

### ISSUE THREAD

**Issue by Rasulwebs** [jolbol1/nextjs-velite-blog-template#4]
Is there an admin dashboard site to manage this blog site.
For example, to post a blog quickly and easily, 
or will all blog content be created in a separate file and 
written manually?

**Comment by jolbol1** [comment]
This version is just statically managed. I would say its best fits developer portfolio style sites, where you can just keep the blog posts maintained in git. 

Can look at doing an full CMS based blog in the future.
