### ISSUE TITLE
Warning: Prop `className` did not match.

### ISSUE THREAD

**Issue by fabriziofeitosa** [jolbol1/nextjs-velite-blog-template#7]
Console:

![image](https://github.com/jolbol1/nextjs-velite-blog-template/assets/7595031/32834b3c-ebeb-42e6-846d-132ea99c5f6e)

Any suggestions on how to resolve this?

**Comment by jolbol1** [comment]
Hi, apologies hoping to look into this in a bit more detail soon. Not run into this myself. 

Does your HTML have supressHydrationWarnings?
```jsx
<html suppressHydrationWarning>
```

This is necessary when using next-themes: https://github.com/pacocoursey/next-themes#:~:text=%3Chtml%20suppressHydrationWarning%3E

**Comment by jolbol1** [comment]
Hi @fabriziofeitosa did this get solved for you in the end?

**Comment by fabriziofeitosa** [comment]
@jolbol1 It seems that the error disappeared on its own, but using `suppressHydrationWarning={true}` also makes the error go away.
